#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set random Wallpaper 
/home/manu/.local/bin/set_wallpaper.sh &

# Status bar
slstatus &

# Compositor
picom -f &

# Bluetooth Manager Applet
blueman-applet &

# Audio Manager Applet
pasystray &

# Network Manager Applet
nm-applet &

# Blue light filter
redshift -t 6100:3900 -l 41.14961:-8.61099 & 

# Loop
while true; do
	exec dwm >/dev/null 2>&1
done

exec dwm
