#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Get the environment to know which one to boot
graph_env=$1

# dwm exclusive execs
if [ "$graph_env" = "dwm" ]
then
    # dunst (notification server)
    dunst -conf ~/.config/dunst/dunstrc &

    # dwm status
    # /home/manu/.suckless/dwm-bar/dwm_bar.sh &

    # slstatus
    exec slstatus &

    # Compositor
    picom -f &

    # Wallpaper
    nitrogen --restore &

    # Init pasystray (sys tray applet for pulseaudio)
    # it is here because for some reason KDE starts it
    # automatically so I would just get 2 of it
    pasystray &
fi

# Display resolution
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 165 &

# Clipboard manager
parcellite &

# Init nmgui so it goes in the systray
nm-applet &

# redshift (blue light filter)
redshift -t 6100:3900 -l 41.14961:-8.61099 &

# Set the GTK theme to a dark theme
export GTK_THEME=Arc-Dark

# Loop
while true; do
    eval "$graph_env >/dev/null 2>&1"
done

# Exec WM/DE
eval $graph_env
